[build]
  command = "npm run build && npx netlify functions:build"
  publish = "out" 
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200